VIDEO-XXXX update to 5.2.0
twilio/video-quickstart-ios pull request #654
Opened 2022-08-24 22:09 UTC by dipankadas

#### 5.2.0 (August 24, 2022)

* Programmable Video iOS SDK 5.2.0 [[XCFramework]](https://github.com/twilio/twilio-video-ios/releases/download/5.2.0/TwilioVideo.xcframework.zip) (checksum: XCFRAMEWORK_CHECKSUM).

Bug Fixes

- Max video bandwidth limits are now applied to each simulcast layer when simulcast is enabled, and the expected behavior for max video bitrates with simulcast is better documented.
- Fixed several bugs that could cause crashes and deadlocks when a Room is disconnected / destroyed.
- Fixed a use-after-free bug associated with tasks posted to TaskQueue that could lead to undefined behavior.
- Fixed a bug which could cause a crash in IceConnectionActivityMonitor when reconnecting to or disconnecting from a Room.
- Fixed a race condition where subscribed callbacks for Remote Participant could be raised for tracks that have been ended.

Known Issues

- Audio playback fails in some cases when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. [#34](https://github.com/twilio/twilio-video-ios/issues/34)
- H.264 video might become corrupted after a network handoff. [#147](https://github.com/twilio/twilio-video-ios/issues/147)
- iOS devices do not support more than three H.264 encoders. Refer to [#17](https://github.com/twilio/twilio-video-ios/issues/17) for suggested work arounds.
- Publishing H.264 video at greater than 1280x720 @ 30fps is not supported. If a failure occurs then no error is raised to the developer. [ISDK-1590]

Size Impact

Architecture | Compressed Size | Uncompressed Size
------------ | --------------- | -----------------
Universal | 4.7 MB | 10.9 MB
arm64 | 4.7 MB | 10.9 MB

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

2022-08-24 22:12 UTC, mmartikainen requested changes

2022-08-24 22:12 UTC, mmartikainen commented on VideoQuickStart/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "size" : "1024x1024"
Unintentional?

2022-08-25 14:36 UTC, dipankadas commented on VideoQuickStart/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "size" : "1024x1024"
Oh yes. I need to remove this file.

2022-08-25 15:46 UTC, mmartikainen approved these changes

2022-08-25 15:47 UTC, merged